export const DEFAULT_GAP = 12
export const DEFAULT_MAX_VISIBLE_TOAST = 3
export const DEFAULT_RAC_MAX_VISIBLE_TOAST = Number.MAX_SAFE_INTEGER
export const DEFAULT_SCALE_FACTOR = 0.05
export const DEFAULT_TOAST_WIDTH = 460
export const DEFAULT_TOAST_TIMEOUT = 4000
